<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 .\static\scene.gltf
Author: C.U.V (https://sketchfab.com/C.U.V)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plush-unicorn-fd6f044ab8164a7e947f69fbe58435ee
Title: Plush Unicorn
-->

<script>
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/scene.gltf')
</script>

{#if $gltf}
  <T is={ref} {...$$restProps}>
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
      <T.Mesh
        geometry={$gltf.nodes.Plush_Unicorn_Plush_Unicorn_0.geometry}
        material={$gltf.materials.Plush_Unicorn}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </T.Group>

    <slot {ref} />
  </T>
{/if}
